### ISSUE TITLE
List supported browsers

### ISSUE THREAD

**Issue by literalpie** [georgipeltekov/ngx-file-drop#113]
I can see by searching issues that Safari and IE are not supported. It would be nice if this was more clearly documented.

**Comment by DonaldAlan** [comment]
The demo page https://georgipeltekov.github.io/  works on chrome for me, but not on firefox (Version 64.0.2)

**Comment by georgipeltekov** [comment]
@DonaldAlan  I fix the demo. The problem was not in the library, but in the demo itself (it seems that in Firefox they just change the property of lastModifiedDate, to be just lastModified)

**Comment by blackn1ght** [comment]
I've just included this in my project, and it's not working on Firefox 64.0.2, but it is working on Chrome 71.0.3578.

**Comment by DonaldAlan** [comment]
Thanks, https://georgipeltekov.github.io/ works now, from chrome, firefox, and edge.

**Comment by DonaldAlan** [comment]
But the demo doesn't work in ie. A colleague suggests you may need to enable ie polyfill.

**Comment by georgipeltekov** [comment]
@blackn1ght  what is not working exactly? Is there any error or? Could you provide a stackblitz example?

@DonaldAlan the problem is not only with the polyfills. Actually the library relies on html5 file API functionality, which is not supported by  IE
https://github.com/leonadler/drag-and-drop-across-browsers#microsoft-internet-explorer

**Comment by blackn1ght** [comment]
@georgipeltekov There's no error no, just nothing happens when dragging a file into the drop zone!

I'm going to try to upgrade my project to angular 7 and ngx-file-drop 5.0.0 (although struggling with `ng update` due to having fontawesome private repo in my `.npmrc` file).  If it's still not working on ng7 and ngxfd v5, I'll let you know.

**Comment by georgipeltekov** [comment]
Something must happen, that is why I asked for stackblitz example. Here, I just created one, copying the code from the readme, as you can see it is using the same angular and ngx-file-drop versions like you:
https://angular-1ommmp.stackblitz.io/

Just tested it with the latest firefox version.

**Comment by blackn1ght** [comment]
@georgipeltekov That stackblitz doesn't work for me in Firefox, but works in Chrome & Edge.

I get this error in Firefox console, but not in the other browsers:

```
NotFoundError: Node was not found ext-f0c7bc0f805f938de9dfb.js:1
543/</Ke</t.prototype.close/<https://c.staticblitz.com/assets/ext-f0c7bc0f805f938de9dfb.js:1:116989

```

The only extensions I have installed on Firefox is the Reddit Enhancement Suite.

**Comment by georgipeltekov** [comment]
I updated the readme, describing that IE and Safari are not supported
