### ISSUE TITLE
Event UploadEvent to a type Input

### ISSUE THREAD

**Issue by Tang8** [georgipeltekov/ngx-file-drop#118]
Hello,

I have another question : Can i set to an input your `UploadEvent` ? 
If i can, can you tell me how can i do it.

Thanks for read this question.

**Comment by georgipeltekov** [comment]
UploadEvent is customized event and it comes from the library, while the input type is from the standard html5. There are different things, coming from different places

**Comment by fergardi** [comment]
@georgipeltekov is there any way to convert from UploadEvent to the classic HTML5 Event? I'm using a third party plugin (https://www.npmjs.com/package/ngx-image-cropper) to edit and crop an image, and it receives an HTML5 Event from an input change, and would like to use your plugin to add a drag&drop functionality to the file selection.

**Comment by georgipeltekov** [comment]
@fergardi  I am not sure what are you want to achieve? Can you give a stackblitz example for instance, so I can check it into more details. Also what version of the library are you using?

**Comment by fergardi** [comment]
Nevermind @georgipeltekov , I found a very similar question for my problem in the ngx-image-cropper repository. It turns out another person was trying to achieve the same I was, that is, mixing your ngx-file-drop library with the ngx-image-cropper library. Just capturing the dropEvent and passing it to the image cropper.

https://github.com/Mawi137/ngx-image-cropper/issues/9#issuecomment-360990649

It is working now!

Thanks for your time!
