### ISSUE TITLE
FileSystemFileEntry lacks of 'type' for CSV files

### ISSUE THREAD

**Issue by p0rsche** [georgipeltekov/ngx-file-drop#149]
When using dropzone, I have a strange behavior: while event.dataTransfer for items correctly recognizes file's type, after using .file() method of FileSystemFileEntry it returns a File with empty type for CSV files. When using standard input all is OK

**Comment by georgipeltekov** [comment]
Hi,

unfortunately this is  limitation of the library. Basically we need to either have the functionality for folder upload or live with the fact that sometimes the types will be empty.  If we prefer event.dataTransfer.items  over event.dataTransfer.files, as it is currently, this will be the case, otherwise the types will be ok, but we will have problems with the folders. 

You can easily determine the type by the extension.
