### ISSUE TITLE
how do I style the file-drop element?

### ISSUE THREAD

**Issue by AndreasSchmid1** [georgipeltekov/ngx-file-drop#21]
how do I style the file-drop element, for example changing the color?

**Comment by georgipeltekov** [comment]
you can use the customstyle property (https://github.com/georgipeltekov/ngx-file-drop#parameters) to pass your css class name. After that just use the standard css to style it.

**Comment by AndreasSchmid1** [comment]
customstyle="filedrop" and

`.filedrop{
    margin: auto;
    height: 100px;
    border: 2px dotted #0782d0;
    border-radius: 30px;
}`

is not working. A small introduction how to use the customstyle property would be very useful

**Comment by georgipeltekov** [comment]
where i this filedrop css class defined. Try putting it into styles.css to be sure that it is included in the component.

**Comment by AndreasSchmid1** [comment]
Yes I did this. I was able to change the color when setting customstyle="filedrop" and class="filedrop" but i think this is not the expected behavior

**Comment by georgipeltekov** [comment]
could you please provide some sources, where this can be reproduced?

**Comment by AndreasSchmid1** [comment]
Unfortunately I dont know how to use plnkr. 

`<div fxLayout="row">
     <file-drop customstyle="filedrop" (onFileDrop)="dropped($event)"   >
     <input style="display: none;" type="file" accept=".vmic" (change)="onFileSelected($event)" #file multiple >
     <button mat-icon-button (click)="file.click()" mdTooltip="Load/Change an existing Configuration File" ><mat-icon>file_upload</mat-icon></button>
         
     </file-drop>
   </div>`
`.filedrop{
    margin: auto;
    height: 100px;
    border: 2px dotted #000000;
    border-radius: 30px;
  }`

I am using ngx-file-drop 2.0.1 with angular 4.4.6.

If u cant see the error with your tests i will try to create a plunker the next days

**Comment by georgipeltekov** [comment]
where is this filedrop class defined? I am almost 100% sure that the location is not included properly. For instance , if you are using angular-cli in your angular-cli.json file probably you have something like this:
"styles": [
        "styles.css"
      ],

in that case this class definition should be in this styles.css file, the global one

**Comment by AndreasSchmid1** [comment]
I am defining everything in a component.

@Component({
  selector: 'app-uploadchunk',
  templateUrl: './uploadchunk.component.html',
  styleUrls: ['./uploadchunk.component.css']
})

Ok I also think i made a mistake. I will try to fix it later. Thank you very much for help!

**Comment by georgipeltekov** [comment]
as I mentioned, try defining it in styles.css file

**Comment by AndreasSchmid1** [comment]
I did this and it worked. thank you very much. I am still a very beginner in web and angular

**Comment by alexcoroza** [comment]
Why is that putting custom class works when I put it in styles.scss but not working if i put it in my component's scss file. I know my component's scss file is linked correctly because all the styles there are taking effect except for the custom file drop class styles

**Comment by yonnyviz** [comment]
@alexcoroza Same happens to me... For some reason, "customstyle" property does not recognize the classes from the component's stylesheet and only recognize it from the main's project stylesheet "styles.scss"

**Comment by chrisvm** [comment]
@yonnyviz Did you ever got this to work? Using version 6.0.1 with Angular 7 and I'm having the same problem. I'm thinking this could be a problem with the way that angular "encapsulates" stylesheets to only apply to DOM elements from the component. I didn't want to pollute the global stylesheet if I could avoid it.

**Comment by yonnyviz** [comment]
@chrisvm No I couldn't get this to work in the component's stylesheet. Since I was short of time I created a stylesheet file where I wrote the styles I needed and added that file to the stylesheet folder architecture I use (checkout [SMACSS](http://smacss.com/)) which is then imported into the global stylesheet.

I remember checking out this [article](https://blog.angular-university.io/angular-host-context/) about angular encapsulation and how to style encapsulated components but I found it a little too complicated since I was short of time.

**Comment by AllanJeyamithran** [comment]
How to Disable a ngx-file-drop box ?

**Comment by hoeni** [comment]
Angular style encapsulation doesn't allow accessing styles inside components by name. This is why you'll would have to put into the global CSS to access it. However, this is an ugly hack, because it disturbs keeping your stuff together in isolated components.

I managed to get this to work in a less hackish (but still ugly) way by penetrating the CSS-encapsulation with the synthetic `::ng-deep` class, so I could keep the styling together with the rest of the component and give every appearance of ngx-file-drop a different look, depending on its context:

```scss
ngx-file-drop ::ng-deep > div {
  // styling for the outer drop box
  > div {
    // styling for the inner box (template)
  }
}
```
