### ISSUE TITLE
ERROR in Cannot resolve type entity i7.NgxFileDropModule to symbol

### ISSUE THREAD

**Issue by mordehi** [georgipeltekov/ngx-file-drop#213]
NgxFD Version: 9.0.1
NG Version: 9.1.8

Steps:

Install package: "npm i --save ngx-file-drop"
Add import to top of app.module: "import {NgxFileDropModule} from 'ngx-file-drop';"
Add NgxFileDropModule module to import list for module.

After ng start i'm getting "ERROR in Cannot resolve type entity i7.NgxFileDropModule to symbol"

Thanks.

**Comment by georgipeltekov** [comment]
Could you please share a stackblitz example, also you can check the example in the read.me file.

**Comment by mordehi** [comment]
i did exactly like the example from the read.me

**Comment by georgipeltekov** [comment]
Ok, can you share a stackblitz example. There is nothing i7 related in the library, and as the library is widely used ( also there are no new versions, that could brought some regression) I think that the problem is in your setup. But I cannot do anything more, without to see your code and how you made the setup.
