### ISSUE TITLE
Argument of type 'UploadFile' is not assignable to parameter of type 'Blob'

### ISSUE THREAD

**Issue by wasifale** [georgipeltekov/ngx-file-drop#46]
Hi,
I'm trying to convert the uploaded image into base64 but continuously getting following error.

> Argument of type 'UploadFile' is not assignable to parameter of type 'Blob'

What I'm trying to do is,

    public dropped(event: UploadEvent) {

    console.log(event);

    const files = event.files;

    for (const file of event.files) {

      if (file) {

        const reader = new FileReader();

        reader.onload = this._handleReaderLoaded.bind(this);

        reader.readAsBinaryString(file);

      }

    }

Any help will be appreciated.

**Comment by georgipeltekov** [comment]
Please check examples in the description. 

```
public dropped(event: UploadEvent) {
    this.files = event.files;
    for (const file of event.files) {
      file.fileEntry.file(info => {
        console.log(info);
      });
    }
  }
```

only after you read the file you have access to it
```
 file.fileEntry.file(info => {
        console.log(info);
      });
```

**Comment by wasifale** [comment]
So, all I have to do is to convert `info` in base64. That's what you are trying to say or have I misunderstood it?

**Comment by georgipeltekov** [comment]
yes

**Comment by wasifale** [comment]
Alright, let me try,

**Comment by wasifale** [comment]
This isn't working that way, 
    file.fileEntry.file(info => {
        console.log(info);
      });

info received in this case is not a JSON obj nor a string, and is not convertible to Base64.

**Comment by georgipeltekov** [comment]
of course it is not. Please check #30

**Comment by wasifale** [comment]
I've already worked with it. but the problem here is that **ngx-file-drop** is using `<file-drop></file-drop>` which is not an **Input** element. so we cannot go for the way you mentioned. or if you think we can, please provide a working example.
Thanks.

**Comment by georgipeltekov** [comment]
But why you need the input element. Please try to understand the concept, not to copy/paste different pieces of the code and try to make them work. So the stackoverflow answer show clearly how we can convert File object in base64, right? So in order to make it work we need the file object. The file object is what comes after we read the file entry. So combining with mine example above that would be the info parameter. And you dont need at any point any input element to get the file. The library is designed in this way, so all the users can use the file object in the way they want. 

Once again, please try to understand the concept and not to just copy/paste.

**Comment by wasifale** [comment]
I wasn't copy pasting it, but yeah I was picking the wrong file format and trying to convert it, It is working now, Thanks for your help anyhow.
