### ISSUE TITLE
Bug on Safari

### ISSUE THREAD

**Issue by Zaramao** [georgipeltekov/ngx-file-drop#6]
Hey! The module works great in all other browsers, but in Safari I am getting an error when I drag&drop the files over. The Errors is: `ERROR – TypeError: undefined is not an object (evaluating 'event.dataTransfer.items.length') — file-drop.component.ts:74` and I can't figure out what causes the error.

#Edit - I've set `console.log(event)` on `file-drop.component.ts:71` and it logs the Mouse event, The problem is I guess that in Safari the `event.dataTransfer.items` property does not exist. Screen shot: http://prntscr.com/gkpk9f

**Comment by georgipeltekov** [comment]
Hey,

thank you for your feedback. Could you please test with the latest version I just released (1.0.11), whether the problem is fixed

**Comment by Zaramao** [comment]
Got the new version and now the error is `ERROR – TypeError: event.dataTransfer.files[i].webkitGetAsEntry is not a function. (In 'event.dataTransfer.files[i].webkitGetAsEntry()', 'event.dataTransfer.files[i].webkitGetAsEntry' is undefined) — file-drop.component.ts:83` I have just tried that myself and changed the properties around from `dataTransfer.items` to `dataTransfer.files` but had the same issue.

**Comment by georgipeltekov** [comment]
It appears that folder drag and drop is not supported by Safari. You cna check this very helpful link:
https://github.com/leonadler/drag-and-drop-across-browsers

I publish new version 1.0.12 in order to handle the error above. Please feel free to check it. 
In general as this seems like a browser limitation, I dont see what else we can do here. If you ifnd a workaround for that - feel free to create e pull request and I will check it.

**Comment by Zaramao** [comment]
I see, thank you! :) Will definitely try to solve this issue 👍
