### ISSUE TITLE
Custom style won't work

### ISSUE THREAD

**Issue by avatsaev** [georgipeltekov/ngx-file-drop#65]
If your file-drop component is Encapsulated, how would a foreign class style be applied to the component?
Shouldn't the ViewEncapsulation of the component be set to None?

**Comment by georgipeltekov** [comment]
You can use the customstyle property. You need to define it in your global css styles. You can check #60,

**Comment by avatsaev** [comment]
Thanks it worked, turns out I named the custom class the same as the default class (`.drop-zone`) when defining it in the global state

**Comment by yaniv1988** [comment]
Hi,

I have a file-drop component Encapsulated with customstyle as something like "my-custom-style". Rather than adding to global styles, I prefer using ng::deep to override the encapsulated styles. 

However I see that there is a div tag with class "content" which is causing problems to my styling. It appears the "content" class should be scoped within default class and not independent so that we can be able to override if required. Only way i can proceed now is by overriding something like
`.my-custom-style .content {
display: block !important;
height: inherit !important;
color: black !important;
}`

Refer to the attached zip for my template and styling

[filedrag.zip](https://github.com/georgipeltekov/ngx-file-drop/files/2016683/filedrag.zip)

**Comment by zgluis** [comment]
I also had to mark my properties with !important:

`
.custom-class .content {
  height: 100% !important;
}`
